Porting from Qt5 to Qt6 (#7525)
* Qt5->6: build system fixes

* first set of changes for Qt6 port

* remove superfluous lambda, which causes compile error on MSVC in nested lambda since Qt6 (for whatever reason)

* porting from Qt5 to Qt6; works on Windows

* First try to Update openms_ci_matrix_full.yml to Qt6

* fix pkg names (apparently no -dev pkg for oglwidgets)

* Add GL on Ubuntu?

* try to fix apple-clang compile issue (`ld: unknown option: -no_warn_duplicate_libraries` for OpenMSGUI

* fix compile error ('error C3878: syntax error: unexpected token 'register' following 'jump_statement'') on MSVC when /permissive- flag is used

* AUTO UIC fixes and linux install docs

* fix failing doc build by using ExternalProcess (not clear why vanilla QProcess does not work)

* some license search and replace

* some more license replacements

* more license changes

* update port file

* update vcpkg

* adapt package names

* fix qstring warning

* adapt Win installation to Qt6

* Doxygen's include work differently now. Can use use plain HTML. No doxygen commands (like @ref or @c) allowed.

* fix common params include (just plain HTML allowed in the included file, no more Doxyegen specific command like @ref or @c etc)

* final brush up for Qt6

* check and update Qt6 install instructions for linux

---------

Co-authored-by: Julianus Pfeuffer <jule.pf@gmail.com>
Co-authored-by: Julianus Pfeuffer <j.pfeuffer@fu-berlin.de>
Co-authored-by: Timo Sachsenberg <timo.sachsenberg@uni-tuebingen.de>
Co-authored-by: timosachsenberg <sachsenb@ibminode06.Cs.Uni-Tuebingen.De>
Co-authored-by: Samuel Wein <sam@samwein.com>